ecidadao:
#
# IMPORTANTE: NÃO REMOVA OS ESPAÇOS A ESQUERDA NAS LINHAS
#
# Solicite seu client-id e client-secret via email riscos@economia.gov.br enviando o 
# plano de configuração disponivel em https://softwarepublico.gov.br/social/agatha/manuais-de-usuario/plano-de-configuracao
#
  client-id: agatha.hmg.epl.gov.br
  client-secret: AJfaMZxTfht57YT87bDWFNo9TOicuYFzxB7MtmiWxA3vVKEAc1gxeegVTkqJN3JhA7f4AK8phKm-i5Seo0FTyyo
  pre-established-redirect-uri: http://agatha.hmg.epl.gov.br/gestaoriscos/api/login/openid
  sistema:
    dominio: agatha.hmg.epl.gov.br
    url-pattern-protegido: /**
    redireciona-login-sucesso: http://agatha.hmg.epl.gov.br
    redireciona-logout-sucesso: http://agatha.hmg.epl.gov.br

  # URIS dO AMBIENTE DE TESTES do Login Único
  access-token-uri: https://sso.staging.acesso.gov.br/token
  user-authorization-uri: https://sso.staging.acesso.gov.br/authorize
  validacao-uri: https://sso.staging.acesso.gov.br/jwk

  # URIS dO AMBIENTE DE PRODUÇÃO do Login Único, descomentar as linhas quando solicitar as chaves de produção a SGD
  #access-token-uri: https://sso.acesso.gov.br/token
  #user-authorization-uri: https://sso.acesso.gov.br/authorize
  #validacao-uri: https://sso.acesso.gov.br/jwk

  use-current-uri: false
  scope: openid




